# Generated by Django 6.1 on 2026-08-29 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Magia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=0)),
                ('escola', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField()),
                ('fonte_api', models.CharField(help_text='Slug da magia na API (ex: acid-arrow)', max_length=100)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magias', to='core.personagem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('personagem', 'fonte_api'), name='magia_unica_por_personagem')],
            },
        ),
    ]
