# Generated by Django 6.1 on 2026-08-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magia',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='personagem',
            options={'ordering': ['id']},
        ),
    ]
