# Generated by Django 6.1 on 2026-08-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_magia_options_alter_personagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='magia',
            name='alcance',
            field=models.CharField(blank=True, help_text='Ex: 60 feet, Self, Touch', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='magia',
            name='area_efeito',
            field=models.CharField(blank=True, help_text='Ex: 20-foot radius sphere', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='magia',
            name='cd',
            field=models.CharField(blank=True, help_text='Resumo do teste de resistência, quando houver', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='magia',
            name='componentes',
            field=models.CharField(blank=True, help_text='Ex: V, S, M', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='magia',
            name='concentracao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magia',
            name='dano',
            field=models.CharField(blank=True, help_text='Resumo do dano, quando a magia causa dano', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='magia',
            name='duracao',
            field=models.CharField(blank=True, help_text='Ex: Instantaneous, Concentration, up to 1 minute', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='magia',
            name='material',
            field=models.TextField(blank=True, help_text='Descrição do componente material, quando houver', null=True),
        ),
        migrations.AddField(
            model_name='magia',
            name='ritual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magia',
            name='tempo_conjuracao',
            field=models.CharField(blank=True, help_text='Ex: 1 action, 1 bonus action', max_length=100, null=True),
        ),
    ]
